# nonk8s
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub-event-2
spec:
  topic: newsDetails
  routes:
    default: /dapr/subscribe/newsNotificationDetails
  pubsubname: newsfetch
  scope:
    - news-aggregation-service
    - communication-service



