# nonk8s
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub-event
spec:
  topic: userRegisterDetails
  routes:
    default: /newsAggregation/dapr/subscribe/userRegisterDetails
  pubsubname: pubsub
  scope:
    - user-preferences-service
    - news-aggregation-service
